version: "3"

services: 
  proxy:
    image: nginx:latest
    container_name: proxy-demo
    depends_on: 
      - static
      - app
      - redis
    ports: 
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf

  static:
    container_name: static
    image: nginx:latest 
    ports:
      - 8080:80
    volumes: 
      - ./static/index.html:/usr/share/nginx/html/index.html

  app:
    container_name: app
    build: 
      context: ./app
    ports:
      - 5000:5000
    
  redis:
    container_name: redis
    image: redis:alpine
      
    